<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="ApiTestingFramework by packages" duration-ms="1773" started-at="2020-08-21T09:55:29 PDT" finished-at="2020-08-21T09:55:30 PDT">
    <groups>
    </groups>
    <test name="studentApiTest" duration-ms="1773" started-at="2020-08-21T09:55:29 PDT" finished-at="2020-08-21T09:55:30 PDT">
      <class name="studentApiTest.GetAPITest">
        <test-method status="PASS" signature="baseTest()[pri:0, instance:studentApiTest.GetAPITest@458c1321]" name="baseTest" is-config="true" duration-ms="328" started-at="2020-08-21T09:55:29 PDT" finished-at="2020-08-21T09:55:29 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseTest -->
        <test-method status="PASS" signature="getAPITest()[pri:0, instance:studentApiTest.GetAPITest@458c1321]" name="getAPITest" duration-ms="978" started-at="2020-08-21T09:55:29 PDT" finished-at="2020-08-21T09:55:30 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAPITest -->
      </class> <!-- studentApiTest.GetAPITest -->
      <class name="studentApiTest.PostAPITest">
        <test-method status="PASS" signature="baseTest()[pri:0, instance:studentApiTest.PostAPITest@11438d26]" name="baseTest" is-config="true" duration-ms="0" started-at="2020-08-21T09:55:30 PDT" finished-at="2020-08-21T09:55:30 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseTest -->
        <test-method status="FAIL" signature="testUsingSer()[pri:0, instance:studentApiTest.PostAPITest@11438d26]" name="testUsingSer" duration-ms="261" started-at="2020-08-21T09:55:30 PDT" finished-at="2020-08-21T09:55:30 PDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at apiVerifications.APIVerification.responseCodeValidationWithoutCatch(APIVerification.java:32)
at studentApiTest.PostAPITest.testUsingSer(PostAPITest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUsingSer -->
        <test-method status="PASS" signature="validPostAPITest()[pri:0, instance:studentApiTest.PostAPITest@11438d26]" name="validPostAPITest" duration-ms="43" started-at="2020-08-21T09:55:30 PDT" finished-at="2020-08-21T09:55:30 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validPostAPITest -->
      </class> <!-- studentApiTest.PostAPITest -->
    </test> <!-- studentApiTest -->
  </suite> <!-- ApiTestingFramework by packages -->
</testng-results>
